### ISSUE TITLE
As an ADMIN USER, I am able to sign up and log on for managing a group matcher to the course.

### ISSUE THREAD

**Issue by hk-kaden-kim** [sopra-fs22-group-4/group-matcher-backend#1]
### **Acceptance Criteria**

- [x] the ADMIN USER can enter their email address on the login page.
- [x] If the ADMIN USER is not registered,
   - [x] a message shows that the ADMIN USER must first validate their email address is displayed. A verifying email is sent to the provided email address that includes a time-limited identity validation link.
   - [x] If the verifying email is clicked before expiration, he/she is redirected to the registration page to enter their password.
   - [x] If the verifying email is expired, he/she can click the verification email re-send button on the login page.
   - [x] Upon successful registration, the ADMIN USER logs in automatically and the admin dashboard is shown.
- [x] If the ADMIN USER is already registered,
   - [x] He/She can enter the password.
   - [x] Upon successful login, the admin dashboard is shown.
- [x] Else, a message that specifies the error and how to proceed is displayed.

### **Development Tasks**

- [x] sopra-fs22-group-4/group-matcher-frontend#2
- [x] sopra-fs22-group-4/group-matcher-frontend#3
- [x] sopra-fs22-group-4/group-matcher-frontend#5
- [x] sopra-fs22-group-4/group-matcher-frontend#4
- [x] sopra-fs22-group-4/group-matcher-backend#23
- [x] sopra-fs22-group-4/group-matcher-backend#26
- [x] #46 
- [x] #50 
- [x] sopra-fs22-group-4/group-matcher-frontend#38
- [x] #82
