### ISSUE TITLE
As a STUDENT USER, I want to provide my personal response to the matching quiz.

### ISSUE THREAD

**Issue by hk-kaden-kim** [sopra-fs22-group-4/group-matcher-backend#11]
### **Acceptance Criteria**

- [x] After receiving a link to the matching quiz, the STUDENT USER can click it and be redirected to the correct quiz where all questions defined by the ADMIN USER are displayed together with the remaining time until the deadline for submitting answers.
- [x] The STUDENT USER can provide their answer to each question in the format corresponding to the question’s type; after providing an answer, the question is marked as answered.
- [x] If the STUDENT USER accessed the quiz via a personalized link, their email address is displayed on the page however cannot be edited; else, they have to provide their email address.
- [x] After providing valid input to (at least) all mandatory questions as well as valid email address (if applicable), the STUDENT USER can click the submission button.

### **Development Tasks**

- [x] sopra-fs22-group-4/group-matcher-frontend#10
- [x] #37
- [x] sopra-fs22-group-4/group-matcher-frontend#35
- [x] sopra-fs22-group-4/group-matcher-frontend#36
