### ISSUE TITLE
As an ADMIN USER, I want to be able to create a new matcher specific to my course.

### ISSUE THREAD

**Issue by hk-kaden-kim** [sopra-fs22-group-4/group-matcher-backend#2]
### **Acceptance Criteria**

- [x] The app’s admin dashboard has a button that redirects to a matcher creator which includes group matching information
   - [x] Short Description
   - [x] Single- and Multiple Choice ([US 4](https://github.com/sopra-fs22-group-4/group-matcher-backend/issues/4#issue-1175658192))
   - [x] Matching Algorithm ([US 5](https://github.com/sopra-fs22-group-4/group-matcher-backend/issues/5#issue-1175659934), [US 9](https://github.com/sopra-fs22-group-4/group-matcher-backend/issues/9#issue-1175680126))
   - [x] Timeframe ([US 6](https://github.com/sopra-fs22-group-4/group-matcher-backend/issues/6#issue-1175661330))
   - [x] List of STUDENT email([US 7](https://github.com/sopra-fs22-group-4/group-matcher-backend/issues/7))
- [x] After providing valid input to (at least) all mandatory fields as well as valid credentials (if applicable), the ADMIN USER can click the submission button.
- [x] Upon successful creation of a new matcher, the ADMIN USER is redirected to the matcher’s admin dashboard.
- [x] Else, a message that specifies the error and how to proceed is displayed.

### **Development Tasks**

- [x] sopra-fs22-group-4/group-matcher-frontend#4
- [x] sopra-fs22-group-4/group-matcher-frontend#6
- [x] sopra-fs22-group-4/group-matcher-backend#44
