### ISSUE TITLE
As an ADMIN USER, I want to be able to see and edit my matcher after it was created.

### ISSUE THREAD

**Issue by hk-kaden-kim** [sopra-fs22-group-4/group-matcher-backend#3]
### **Acceptance Criteria**

- [x] Upon the successful login, the ADMIN USER is able to check the list of created matchers on the admin dashboard.
- [x] Below items are editable.
   - [x] Short Description
   - [x] Single- and Multiple Choice ([US 4](https://github.com/sopra-fs22-group-4/group-matcher-backend/issues/4#issue-1175658192))
   - [x] Matching Algorithm ([US 5](https://github.com/sopra-fs22-group-4/group-matcher-backend/issues/5#issue-1175659934), [US 9](https://github.com/sopra-fs22-group-4/group-matcher-backend/issues/9#issue-1175680126))
   - [x] Timeframe ([US 6](https://github.com/sopra-fs22-group-4/group-matcher-backend/issues/6#issue-1175661330))

### **Development Tasks**

- [x] sopra-fs22-group-4/group-matcher-frontend#7
- [x] #32 
- [x] sopra-fs22-group-4/group-matcher-frontend#25
