### ISSUE TITLE
As an ADMIN USER, I want to be able to limit the ability to submit an answer to the matching quiz based on a list of approved STUDENT USERs.

### ISSUE THREAD

**Issue by hk-kaden-kim** [sopra-fs22-group-4/group-matcher-backend#7]
### **Acceptance Criteria**

- [x] On the matcher’s admin page, the ADMIN USER can optionally provide the emails of all STUDENT USERs who are allowed to answer the matching quiz.
- [x] If the ADMIN USER had defined a list of approved STUDENT USERs, any STUDENT USER that fills out the matching quiz has to also provide their email address and confirm their identity ([US 12](https://github.com/sopra-fs22-group-4/group-matcher-backend/issues/12#issue-1175683968)) after submitting their answer.

### **Development Tasks**

- [x] sopra-fs22-group-4/group-matcher-frontend#15
- [x] #65 
- [x] sopra-fs22-group-4/group-matcher-frontend#26
