### ISSUE TITLE
As an ADMIN USER, I want to be able to share my matcher with the relevant STUDENT USERs so that they can fill out the matching quiz within the allowed timeframe.

### ISSUE THREAD

**Issue by hk-kaden-kim** [sopra-fs22-group-4/group-matcher-backend#8]
### **Development Tasks**

- [x] sopra-fs22-group-4/group-matcher-frontend#4
- [x] sopra-fs22-group-4/group-matcher-frontend#10
- [x] sopra-fs22-group-4/group-matcher-backend#35
- [x] #49 
- [x] #50 
- [x] #83
